apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 789949157452.dkr.ecr.ap-northeast-2.amazonaws.com/karyotype-server
  newTag: "2"
- name: gcr.io/learning-274204/karyotype-server
  newTag: "9"
- name: https://789949157452.dkr.ecr.ap-northeast-2.amazonaws.com/karyotype-server
  newTag: "2620"
resources:
- ../base
