apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: https://789949157452.dkr.ecr.ap-northeast-2.amazonaws.com/karyotype-server
  newTag: "2618"
