apiVersion: apps/v1
kind: Deployment
metadata:
  name: karyotype-client-app-deploy
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: karyotype-client-app
  template:
    metadata:
      labels:
        app: karyotype-client-app
    spec:
      containers:
      - image: 789949157452.dkr.ecr.ap-northeast-2.amazonaws.com/karyotype-client:latest
        name: karyotype-client
        env:
        - name: SERVER_URL
          value: "http://a9b46b1546ff411eab9fb066411313b6-1033758553.ap-northeast-2.elb.amazonaws.com:8003/graphql/"
        imagePullPolicy: IfNotPresent