apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: karyotype-server-app-deploy
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: karyotype-server-app
  template:
    metadata:
      labels:
        app: karyotype-server-app
    spec:
      containers:
      #- image: 789949157452.dkr.ecr.ap-northeast-2.amazonaws.com/karyotype-server:latest
      - image: alexmt/argocd-demo:f27903964ba8e31ad89c31379e300a35fe1632a3
        name: karyotype-server
        # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_SERVER_URL
          value: "http://58.229.121.146:8083"